### ISSUE TITLE
Support Dotnet core without the need of referencing Microsoft.NETCore.Portable.Compatibility

### ISSUE THREAD

**Issue by jp7677** [omar/ByteSize#27]
Hi there,

I'm using your nice library in a dotnet core 1.1 project. Unfortunately I'm seeing errors like

`The type 'ValueType' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'. [netcoreapp1.1]`

I can somehow work around this by referencing `Microsoft.NETCore.Portable.Compatibility` but it would be nice if your library would support dotnet core directly.

Kind regards

**Comment by omar** [comment]
Hey @jp7677,

Are you able to update the package to version 1.1.1? That version should correctly support .NET Core. You can see the changes since then here https://github.com/omar/ByteSize/releases.

Let me know if that works.

**Comment by jp7677** [comment]
Hi,

Thanks for your response, I'm using the latest version from nuget, 1.2.4.
Should I downgrade?

**Comment by omar** [comment]
Oh, I misread your original comment. Let me take a look at this later tonight and I'll get back to you. I thought the library supported .NET Core just fine, but I guess I missed something.

**Comment by omar** [comment]
Can you see if [v1.2.5-alpha](https://www.nuget.org/packages/ByteSize/1.2.5-alpha) works for you? I ended including `NETStandard.Library` as a dependency for netstandard, but I'm not 100% sure that's what I'm supposed to do.

**Comment by jp7677** [comment]
Unfortunately using 1.2.5-aplha didn't work. Looking at you code I guess some more work is needed for proper net core support. I gave it a try, see https://github.com/omar/ByteSize/pull/28.

**Comment by omar** [comment]
I just published [alpha2](https://www.nuget.org/packages/ByteSize/1.2.5-alpha2). Can you see if that works for you?

**Comment by jp7677** [comment]
Hi @omar, yes, that one works perfectly for me. Thanks for continuing my work!

**Comment by jp7677** [comment]
PS: Please do not use the complete netstandard library as dependency in the project.json (https://github.com/omar/ByteSize/blob/netstandard/src/ByteSizeLib/project.json), it's advisable to refer only that packages that you really need for libraries like yours. 
See also https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/reducing-dependencies.

**Comment by omar** [comment]
Thanks for pointing that out, but it seems to contradict [this answer](https://github.com/dotnet/standard/issues/71#issuecomment-255158230). Looks like to future proof this it's best we depending on the full library. Let me know your thoughts.

**Comment by omar** [comment]
To stay inline with older versions of the package, I went ahead and only referenced the specific packages we need. I'll kick the can down the road for when to depend on the netstandard library.

**Comment by omar** [comment]
I just published [v1.2.5](https://www.nuget.org/packages/ByteSize/1.2.5) with the proper support for .NET Standard 1.0. Thanks for your help.

**Comment by jp7677** [comment]
Thanks for the link, I wasn't aware that ideas are shifting towards referencing the complete package. I guess it's a wise move to do so with netstandard2.
You are welcome!

**Comment by jp7677** [comment]
PS: You still have a reference to the no longer existing ByteSize.Dotnet.csproj in your readme. Furthermore since I guess you are running the unit tests in netcore only you can remove the last #if NETCOREAPP1_1 as well.

**Comment by omar** [comment]
Thanks for pointing that out. I just fixed both issues.

**Comment by jp7677** [comment]
Cheers! ;)
